### ISSUE TITLE
Acceleration values

### ISSUE THREAD

**Issue by arpitg1304** [cagataysari/yostlab_imu#1]
Hi, are you sure that the acceleration values are correct.?

Which unit is this? What should I multiply to this value to get the absolute acceleration?

**Comment by cagataysari** [comment]
hello, I coded this node about a year ago and I visualized the output in RViz. By then everything seemed to be working just fine. The acceleration values are published to the /imu topic if I am not sure. If something is wrong, feel free to open up a PR. Acceleration is in metric system. Hope this helps

**Comment by arpitg1304** [comment]
I figured it out. These values are not in metric scale and I will open a PR.

Thank You for creating this package. 

Did you actually use this sensor for any project? We see a lot of acceleration in X direction even if we move the IMU strictly in Z diection

**Comment by cagataysari** [comment]
Yes I have used it. You can change x,y,z direction paradigm to ENU,NED

**Comment by cagataysari** [comment]
https://github.com/cagataysari/yostlab_imu/blob/master/src/YostLabDriver.cpp#L31

**Comment by cagataysari** [comment]
https://github.com/cagataysari/yostlab_imu/blob/master/src/YostLabDriver.cpp#L54

**Comment by cagataysari** [comment]
https://github.com/cagataysari/yostlab_imu/blob/master/src/YostLabDriver.cpp#L132

these methods will help you to correcty assing your axises

**Comment by cagataysari** [comment]
I used the imu but this package is not the package used in product. This is kind of an experimental package that I have open-sourced
